ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS salary_range TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS location TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS job_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_size TEXT NOT NULL DEFAULT '';
